In [2]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [3]:
# Load Iris Dataset
df= datasets.load_iris(as_frame=True).frame

In [7]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [8]:
X= df.drop("target", axis=1)
y=df["target"]

In [9]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y , test_size=0.3 , random_state=42, stratify=y
)

In [12]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [14]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

In [ ]:
# Model