In [30]:
import pandas as pd

In [31]:
df=pd.read_csv("/Users/ravihw18/ML-Algorithms/13-RNN/Dataset/IMDB Dataset.csv")

In [32]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [33]:
df.drop_duplicates(inplace=True)

In [34]:
df.shape

(49582, 2)

## Pre-Processing

### 1. Converting to Lowercase

In [35]:
df["review"] = df["review"].str.lower()

### 2. Removing the URLs

In [36]:
import re

def remove_urls(text):
    text =re.sub(r"http\S+", "", text)   # (pattern, replace element, string) 
    return text

df["review"] = df["review"].apply(remove_urls)

### 3. Removing Punctuations

In [38]:
def remove_punctuations(text):
    text=re.sub(r"[^A-Za-z0-9\s]", "", text)
    return text

df["review"] = df["review"].apply(remove_punctuations)

### 4. Removing HTML

In [40]:
def remove_html(text):
    text=re.sub(r"<.*?>", "", text)
    return text

df["review"] = df["review"].apply(remove_html)

### 5. Removing the StopWords

In [41]:
import nltk # natural language tool kit
# nltk.download("punkt")
# nltk.download("punkt_tab")
# nltk.download("stopwords")

In [42]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [43]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words= stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [44]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive